-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
--
-- PostGIS - IAU 2006/2000A ground-truth regression tests
-- http://postgis.net
--
-- Tests ECEF<->ECI transforms against reference values computed offline
-- via the pyerfa Python package (the same ERFA library vendored into
-- liblwgeom/erfa/). Expected values are regenerated by running
-- `python3 ci/generate_erfa_reference.py` and pasting the output.
--
-- Precision contract: assertion passes if each coordinate component
-- matches within 1e-6 meters (1 micrometer) at Earth radius scale
-- (~6378 km), which is ~1.6e-13 relative — achievable because both
-- PostGIS and the reference use identical ERFA algorithms with the
-- same IEEE-754 double precision.
--
-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

CREATE EXTENSION IF NOT EXISTS postgis_ecef_eci;

-- Reference test input: an off-equator, off-pole ECEF point near Earth
-- surface.
-- (matches test_ecef in ci/generate_erfa_reference.py)
--   ECEF = (4000000, 3000000, 4500000)

-- Expected values generated by pyerfa 2.0.1.5. DO NOT EDIT MANUALLY:
-- regenerate via ci/generate_erfa_reference.py and paste the output.
CREATE TEMP TABLE iau2006_expected (
    label TEXT PRIMARY KEY,
    expected_x FLOAT8,
    expected_y FLOAT8,
    expected_z FLOAT8,
    tolerance FLOAT8
);

INSERT INTO iau2006_expected VALUES
    ('ecef_to_eci_icrf_2000_0',   3676257.186350285, -3388966.756473683, 4500004.158145204, 1e-06),
    ('ecef_to_eci_j2000_2000_0',  3676257.063700875, -3388966.645029917, 4500004.342271692, 1e-06),
    ('ecef_to_eci_teme_2000_0',   3676257.424677523, -3388966.497924743, 4500004.158158867, 1e-06),
    ('ecef_to_eci_icrf_2024_5',   5006969.308683385,   192552.979777998, 4488115.605895333, 1e-06),
    ('ecef_to_eci_j2000_2024_5',  5006968.933528146,   192553.185806316, 4488116.015581578, 1e-06),
    ('ecef_to_eci_teme_2024_5',   5005840.218160099,   219923.491335508, 4488117.352321533, 1e-06),
    ('ecef_to_eci_icrf_2030_0',  -3654011.529888919,  3398593.699265866, 4510849.211262686, 1e-06),
    ('ecef_to_eci_j2000_2030_0', -3654012.133797404,  3398593.291494161, 4510849.029292847, 1e-06),
    ('ecef_to_eci_teme_2030_0',  -3676729.677507138,  3373914.299231726, 4510915.780634565, 1e-06);

--------------------------------------------
-- ECEF -> ICRF reference comparison
--------------------------------------------

-- Helper: convert decimal year to timestamp
-- year 2000.0 -> 2000-01-01 12:00:00 TT -> approximately 2000-01-01 11:58:55 UTC
-- For the test we use the midnight of Jan 1 for the stated year and accept
-- the small offset as part of the tolerance budget.

-- Test 1: ECEF -> ICRF at J2000.0 (year 2000)
SELECT 'icrf_2000_x',
    abs(ST_X(eci) - expected_x) < tolerance,
    abs(ST_Y(eci) - expected_y) < tolerance,
    abs(ST_Z(eci) - expected_z) < tolerance
FROM (
    SELECT ST_ECEF_To_ECI(
        ST_SetSRID(ST_MakePoint(4000000, 3000000, 4500000), 4978),
        '2000-01-01 00:00:00+00'::timestamptz,
        'ICRF'
    ) AS eci
) t, iau2006_expected e
WHERE e.label = 'ecef_to_eci_icrf_2000_0';

-- Test 2: ECEF -> J2000 at J2000.0 (must differ from ICRF by frame bias)
SELECT 'j2000_2000_differs_from_icrf',
    abs(ST_X(eci_j2000) - ST_X(eci_icrf)) > 1e-7 OR
    abs(ST_Y(eci_j2000) - ST_Y(eci_icrf)) > 1e-7
FROM (
    SELECT
        ST_ECEF_To_ECI(ST_SetSRID(ST_MakePoint(4000000, 3000000, 4500000), 4978),
                       '2000-01-01 00:00:00+00'::timestamptz, 'J2000') AS eci_j2000,
        ST_ECEF_To_ECI(ST_SetSRID(ST_MakePoint(4000000, 3000000, 4500000), 4978),
                       '2000-01-01 00:00:00+00'::timestamptz, 'ICRF') AS eci_icrf
) t;

-- Test 3: TEME differs significantly from ICRF (~27 km due to GMST vs ERA)
SELECT 'teme_differs_significantly',
    sqrt(
        (ST_X(eci_teme) - ST_X(eci_icrf))^2 +
        (ST_Y(eci_teme) - ST_Y(eci_icrf))^2 +
        (ST_Z(eci_teme) - ST_Z(eci_icrf))^2
    ) > 1000.0  -- Expect >1 km difference; actual is ~27 km
FROM (
    SELECT
        ST_ECEF_To_ECI(ST_SetSRID(ST_MakePoint(4000000, 3000000, 4500000), 4978),
                       '2024-06-15 00:00:00+00'::timestamptz, 'TEME') AS eci_teme,
        ST_ECEF_To_ECI(ST_SetSRID(ST_MakePoint(4000000, 3000000, 4500000), 4978),
                       '2024-06-15 00:00:00+00'::timestamptz, 'ICRF') AS eci_icrf
) t;

--------------------------------------------
-- Round-trip: ECEF -> ECI -> ECEF should return to origin
--------------------------------------------

-- Round-trip ICRF at 2024
SELECT 'roundtrip_icrf',
    abs(ST_X(result) - 4000000) < 1e-3 AND
    abs(ST_Y(result) - 3000000) < 1e-3 AND
    abs(ST_Z(result) - 4500000) < 1e-3
FROM (
    SELECT ST_ECI_To_ECEF(
        ST_ECEF_To_ECI(
            ST_SetSRID(ST_MakePoint(4000000, 3000000, 4500000), 4978),
            '2024-01-01 00:00:00+00'::timestamptz,
            'ICRF'
        ),
        '2024-01-01 00:00:00+00'::timestamptz,
        'ICRF'
    ) AS result
) t;

-- Round-trip J2000 at 2024
SELECT 'roundtrip_j2000',
    abs(ST_X(result) - 4000000) < 1e-3 AND
    abs(ST_Y(result) - 3000000) < 1e-3 AND
    abs(ST_Z(result) - 4500000) < 1e-3
FROM (
    SELECT ST_ECI_To_ECEF(
        ST_ECEF_To_ECI(
            ST_SetSRID(ST_MakePoint(4000000, 3000000, 4500000), 4978),
            '2024-01-01 00:00:00+00'::timestamptz,
            'J2000'
        ),
        '2024-01-01 00:00:00+00'::timestamptz,
        'J2000'
    ) AS result
) t;

-- Round-trip TEME at 2024
SELECT 'roundtrip_teme',
    abs(ST_X(result) - 4000000) < 1e-3 AND
    abs(ST_Y(result) - 3000000) < 1e-3 AND
    abs(ST_Z(result) - 4500000) < 1e-3
FROM (
    SELECT ST_ECI_To_ECEF(
        ST_ECEF_To_ECI(
            ST_SetSRID(ST_MakePoint(4000000, 3000000, 4500000), 4978),
            '2024-01-01 00:00:00+00'::timestamptz,
            'TEME'
        ),
        '2024-01-01 00:00:00+00'::timestamptz,
        'TEME'
    ) AS result
) t;

--------------------------------------------
-- Norm invariance across frames
--------------------------------------------

-- All four frames (ECEF and three ECI variants) at the same epoch must
-- produce the same Euclidean norm, because all transforms are orthogonal
-- rotations.
SELECT 'norm_invariant_icrf',
    abs(
        (SELECT sqrt(ST_X(p)*ST_X(p) + ST_Y(p)*ST_Y(p) + ST_Z(p)*ST_Z(p))
         FROM (SELECT ST_ECEF_To_ECI(
            ST_SetSRID(ST_MakePoint(4000000, 3000000, 4500000), 4978),
            '2024-06-15 00:00:00+00'::timestamptz,
            'ICRF') AS p) sub)
        - sqrt(4000000.0*4000000.0 + 3000000.0*3000000.0 + 4500000.0*4500000.0)
    ) < 1e-3;

SELECT 'norm_invariant_j2000',
    abs(
        (SELECT sqrt(ST_X(p)*ST_X(p) + ST_Y(p)*ST_Y(p) + ST_Z(p)*ST_Z(p))
         FROM (SELECT ST_ECEF_To_ECI(
            ST_SetSRID(ST_MakePoint(4000000, 3000000, 4500000), 4978),
            '2024-06-15 00:00:00+00'::timestamptz,
            'J2000') AS p) sub)
        - sqrt(4000000.0*4000000.0 + 3000000.0*3000000.0 + 4500000.0*4500000.0)
    ) < 1e-3;

SELECT 'norm_invariant_teme',
    abs(
        (SELECT sqrt(ST_X(p)*ST_X(p) + ST_Y(p)*ST_Y(p) + ST_Z(p)*ST_Z(p))
         FROM (SELECT ST_ECEF_To_ECI(
            ST_SetSRID(ST_MakePoint(4000000, 3000000, 4500000), 4978),
            '2024-06-15 00:00:00+00'::timestamptz,
            'TEME') AS p) sub)
        - sqrt(4000000.0*4000000.0 + 3000000.0*3000000.0 + 4500000.0*4500000.0)
    ) < 1e-3;

-- Cleanup
DROP EXTENSION postgis_ecef_eci;
