/**********************************************************************
 *
 * PostGIS - Spatial Types for PostgreSQL
 * http://postgis.net
 *
 * Apple Metal GPU compute backend for batch coordinate transforms.
 * Uses Objective-C for the Metal API; kernels are in
 * gpu_metal_kernels.metal, compiled and embedded at build time.
 *
 **********************************************************************/

#include "../../postgis_config.h"

#ifdef HAVE_METAL
#if defined(__APPLE__)

#import <Metal/Metal.h>
#import <Foundation/Foundation.h>
#include "../lwgeom_gpu.h"
#include "../lwgeom_log.h"
#include <string.h>
#include <math.h>
#include <mach/vm_page_size.h>

/* Embedded metallib generated by xxd -i at build time */
#include "gpu_metal_kernels_metallib.h"

/*
 * Parameter structs matching the Metal kernel constant buffers.
 * These must stay in sync with the structs in gpu_metal_kernels.metal.
 * NOTE: Metal does not support double. All GPU-side data uses float.
 * Host side converts double <-> float at dispatch boundaries.
 */
struct RotateZParams
{
	uint32_t stride;
	uint32_t npoints;
	float cos_t;
	float sin_t;
};

struct RotateZMEpochParams
{
	uint32_t stride;
	uint32_t npoints;
	uint32_t m_offset;
	int32_t  direction;
};

struct RadConvertParams
{
	uint32_t stride;
	uint32_t npoints;
	float scale;
};

/*
 * Convert interleaved double coordinate data to float for Metal dispatch.
 * Returns a malloc'd float array that the caller must free.
 */
static float *
metal_doubles_to_floats(const double *src, size_t count)
{
	float *dst = malloc(count * sizeof(float));
	if (!dst)
		return NULL;
	for (size_t i = 0; i < count; i++)
		dst[i] = (float)src[i];
	return dst;
}

/*
 * Convert float results from Metal back to double coordinate data.
 */
static void
metal_floats_to_doubles(double *dst, const float *src, size_t count)
{
	for (size_t i = 0; i < count; i++)
		dst[i] = (double)src[i];
}

/*
 * File-scope statics: cached Metal objects.
 * PostgreSQL runs one backend per process, so no locking needed.
 */
static int metal_initialized = 0;
static int metal_disabled = 0;
static char metal_device_name[256] = {0};

static id<MTLDevice> mtl_device = nil;
static id<MTLCommandQueue> mtl_queue = nil;
static id<MTLLibrary> mtl_library = nil;
static id<MTLComputePipelineState> mtl_pipeline_rotate_z = nil;
static id<MTLComputePipelineState> mtl_pipeline_rotate_z_m_epoch = nil;
static id<MTLComputePipelineState> mtl_pipeline_rad_convert = nil;

/* Threadgroup size for compute dispatches */
#define METAL_THREADGROUP_SIZE 256

/**
 * Check whether a pointer and length are suitable for zero-copy
 * Metal buffer wrapping via newBufferWithBytesNoCopy.
 *
 * Requirements: pointer must be page-aligned and length must be
 * a multiple of the VM page size.
 *
 * Returns 1 if eligible, 0 otherwise.
 */
static int
metal_can_zerocopy(const void *ptr, size_t len)
{
	size_t page_size = vm_page_size;
	if ((uintptr_t)ptr % page_size != 0)
		return 0;
	if (len % page_size != 0)
		return 0;
	return 1;
}

/**
 * Initialize the Metal GPU backend.
 * Creates device, command queue, loads embedded metallib, and
 * creates compute pipeline states for each kernel.
 *
 * Returns 1 on success, 0 on failure.
 */
int
lwgpu_metal_init(void)
{
	NSError *error = nil;
	id<MTLFunction> fn = nil;

	if (metal_initialized)
		return !metal_disabled;

	metal_initialized = 1;

	@autoreleasepool
	{
		/* Get the default Metal device */
		mtl_device = MTLCreateSystemDefaultDevice();
		if (!mtl_device)
		{
			LWDEBUG(1, "Metal: no GPU device found");
			metal_disabled = 1;
			return 0;
		}

		/* Cache device name */
		const char *name = [[mtl_device name] UTF8String];
		if (name)
			strncpy(metal_device_name, name, sizeof(metal_device_name) - 1);
		else
			strncpy(metal_device_name, "Apple GPU", sizeof(metal_device_name) - 1);

		/* Create command queue */
		mtl_queue = [mtl_device newCommandQueue];
		if (!mtl_queue)
		{
			LWDEBUG(1, "Metal: failed to create command queue");
			metal_disabled = 1;
			return 0;
		}

		/* Load embedded metallib.
		 * The metallib data lives in static storage (generated by xxd -i),
		 * so we must NOT let dispatch_data_create free it. Pass an empty
		 * block as the destructor (no-op deallocator). */
		dispatch_data_t lib_data = dispatch_data_create(
			accel_gpu_metal_kernels_metallib,
			accel_gpu_metal_kernels_metallib_len,
			NULL,
			^{});
		mtl_library = [mtl_device newLibraryWithData:lib_data error:&error];
		if (!mtl_library)
		{
			lwnotice("Metal: failed to load metallib: %s",
				 error ? [[error localizedDescription] UTF8String] : "unknown");
			metal_disabled = 1;
			return 0;
		}

		/* Create pipeline state for rotate_z_uniform kernel */
		fn = [mtl_library newFunctionWithName:@"rotate_z_uniform"];
		if (!fn)
		{
			lwnotice("Metal: kernel 'rotate_z_uniform' not found in metallib");
			metal_disabled = 1;
			return 0;
		}
		mtl_pipeline_rotate_z = [mtl_device newComputePipelineStateWithFunction:fn error:&error];
		if (!mtl_pipeline_rotate_z)
		{
			lwnotice("Metal: failed to create rotate_z pipeline: %s",
				 error ? [[error localizedDescription] UTF8String] : "unknown");
			metal_disabled = 1;
			return 0;
		}

		/* Create pipeline state for rotate_z_m_epoch kernel */
		fn = [mtl_library newFunctionWithName:@"rotate_z_m_epoch"];
		if (!fn)
		{
			lwnotice("Metal: kernel 'rotate_z_m_epoch' not found in metallib");
			metal_disabled = 1;
			return 0;
		}
		mtl_pipeline_rotate_z_m_epoch = [mtl_device newComputePipelineStateWithFunction:fn error:&error];
		if (!mtl_pipeline_rotate_z_m_epoch)
		{
			lwnotice("Metal: failed to create rotate_z_m_epoch pipeline: %s",
				 error ? [[error localizedDescription] UTF8String] : "unknown");
			metal_disabled = 1;
			return 0;
		}

		/* Create pipeline state for rad_convert kernel */
		fn = [mtl_library newFunctionWithName:@"rad_convert"];
		if (!fn)
		{
			lwnotice("Metal: kernel 'rad_convert' not found in metallib");
			metal_disabled = 1;
			return 0;
		}
		mtl_pipeline_rad_convert = [mtl_device newComputePipelineStateWithFunction:fn error:&error];
		if (!mtl_pipeline_rad_convert)
		{
			lwnotice("Metal: failed to create rad_convert pipeline: %s",
				 error ? [[error localizedDescription] UTF8String] : "unknown");
			metal_disabled = 1;
			return 0;
		}

		LWDEBUGF(1, "Metal: initialized on %s", metal_device_name);
	}

	return 1;
}

/**
 * Shared Metal compute dispatch helper.
 *
 * Handles the common pattern: create data buffer from float array,
 * create params buffer, encode + dispatch compute kernel, wait for
 * completion, copy results back.
 *
 * @param pipeline  The compute pipeline state for the kernel
 * @param fdata     Float coordinate data (caller-owned, freed on error)
 * @param fdata_len Byte length of fdata
 * @param params    Pointer to kernel parameter struct
 * @param params_len Byte length of params
 * @param npoints   Number of points (thread count for dispatch)
 * @param label     Human-readable kernel name for error messages
 * @return 1 on success, 0 on failure (sets metal_disabled)
 */
static int
metal_dispatch_kernel(id<MTLComputePipelineState> pipeline,
		      float *fdata, size_t fdata_len,
		      void *params, size_t params_len,
		      uint32_t npoints, const char *label)
{
	/* Create Metal buffer for float point data */
	id<MTLBuffer> data_buf = [mtl_device newBufferWithBytes:fdata
							length:fdata_len
						       options:MTLResourceStorageModeShared];
	if (!data_buf)
	{
		lwnotice("Metal: failed to create data buffer for %s", label);
		metal_disabled = 1;
		return 0;
	}

	/* Create constant buffer for kernel parameters */
	id<MTLBuffer> params_buf = [mtl_device newBufferWithBytes:params
							  length:params_len
						         options:MTLResourceStorageModeShared];
	if (!params_buf)
	{
		lwnotice("Metal: failed to create params buffer for %s", label);
		metal_disabled = 1;
		return 0;
	}

	/* Encode and dispatch compute command */
	id<MTLCommandBuffer> cmd_buf = [mtl_queue commandBuffer];
	id<MTLComputeCommandEncoder> encoder = [cmd_buf computeCommandEncoder];
	if (!cmd_buf || !encoder)
	{
		lwnotice("Metal: failed to create command buffer/encoder");
		metal_disabled = 1;
		return 0;
	}

	[encoder setComputePipelineState:pipeline];
	[encoder setBuffer:data_buf offset:0 atIndex:0];
	[encoder setBuffer:params_buf offset:0 atIndex:1];

	NSUInteger tg_size = METAL_THREADGROUP_SIZE;
	if (tg_size > [pipeline maxTotalThreadsPerThreadgroup])
		tg_size = [pipeline maxTotalThreadsPerThreadgroup];

	[encoder dispatchThreads:MTLSizeMake(npoints, 1, 1)
	    threadsPerThreadgroup:MTLSizeMake(tg_size, 1, 1)];
	[encoder endEncoding];

	[cmd_buf commit];
	[cmd_buf waitUntilCompleted];

	if ([cmd_buf status] == MTLCommandBufferStatusError)
	{
		NSError *cb_error = [cmd_buf error];
		lwnotice("Metal: command buffer error in %s: %s",
			 label,
			 cb_error ? [[cb_error localizedDescription] UTF8String] : "unknown");
		metal_disabled = 1;
		return 0;
	}

	/* Copy GPU results back into the caller's float buffer */
	memcpy(fdata, [data_buf contents], fdata_len);
	return 1;
}

/**
 * Uniform-angle Z-rotation on GPU via Metal.
 *
 * @param data    Pointer to interleaved coordinate data
 * @param stride  Byte stride between consecutive points
 * @param n       Number of points
 * @param theta   Rotation angle in radians
 * @return 1 on success, 0 on failure (caller should fallback)
 */
int
lwgpu_metal_rotate_z(double *data, size_t stride, uint32_t n, double theta)
{
	if (metal_disabled || !mtl_device || n == 0)
		return 0;

	@autoreleasepool
	{
		uint32_t stride_doubles = (uint32_t)(stride / sizeof(double));
		size_t total_doubles = (size_t)n * stride_doubles;

		/* Convert double -> float for Metal (no double support on GPU) */
		float *fdata = metal_doubles_to_floats(data, total_doubles);
		if (!fdata)
			return 0;

		size_t fdata_len = total_doubles * sizeof(float);

		struct RotateZParams params;
		params.stride = stride_doubles;
		params.npoints = n;
		params.cos_t = (float)cos(theta);
		params.sin_t = (float)sin(theta);

		if (!metal_dispatch_kernel(mtl_pipeline_rotate_z,
					   fdata, fdata_len,
					   &params, sizeof(params),
					   n, "rotate_z"))
		{
			free(fdata);
			return 0;
		}

		/* Convert float results back to double */
		metal_floats_to_doubles(data, fdata, total_doubles);
		free(fdata);
	}

	return 1;
}

/**
 * Per-point M-epoch Z-rotation on GPU via Metal.
 *
 * @param data     Pointer to interleaved xyzm data
 * @param stride   Byte stride between consecutive points
 * @param n        Number of points
 * @param m_off    Offset of M coordinate in doubles from point start
 * @param dir      -1 for ECI->ECEF, +1 for ECEF->ECI
 * @return 1 on success, 0 on failure (caller should fallback)
 */
int
lwgpu_metal_rotate_z_m_epoch(double *data, size_t stride, uint32_t n,
			     size_t m_off, int dir)
{
	if (metal_disabled || !mtl_device || n == 0)
		return 0;

	@autoreleasepool
	{
		uint32_t stride_doubles = (uint32_t)(stride / sizeof(double));
		size_t total_doubles = (size_t)n * stride_doubles;

		/* Convert double -> float for Metal */
		float *fdata = metal_doubles_to_floats(data, total_doubles);
		if (!fdata)
			return 0;

		size_t fdata_len = total_doubles * sizeof(float);

		struct RotateZMEpochParams params;
		params.stride = stride_doubles;
		params.npoints = n;
		params.m_offset = (uint32_t)m_off;
		params.direction = (int32_t)dir;

		if (!metal_dispatch_kernel(mtl_pipeline_rotate_z_m_epoch,
					   fdata, fdata_len,
					   &params, sizeof(params),
					   n, "rotate_z_m_epoch"))
		{
			free(fdata);
			return 0;
		}

		/* Convert float results back to double */
		metal_floats_to_doubles(data, fdata, total_doubles);
		free(fdata);
	}

	return 1;
}

/**
 * Shut down the Metal backend and release all resources.
 */
void
lwgpu_metal_shutdown(void)
{
	@autoreleasepool
	{
		mtl_pipeline_rad_convert = nil;
		mtl_pipeline_rotate_z_m_epoch = nil;
		mtl_pipeline_rotate_z = nil;
		mtl_library = nil;
		mtl_queue = nil;
		mtl_device = nil;
	}

	metal_initialized = 0;
	metal_disabled = 0;
	metal_device_name[0] = '\0';
}

/**
 * Return the cached Metal device name string.
 */
const char *
lwgpu_metal_device_name(void)
{
	return metal_device_name;
}

#endif /* __APPLE__ */
#endif /* HAVE_METAL */
