/**********************************************************************
 *
 * PostGIS - Spatial Types for PostgreSQL
 * http://postgis.net
 *
 * Apple Metal GPU compute backend for batch coordinate transforms.
 * Uses Objective-C for the Metal API; kernels are in
 * gpu_metal_kernels.metal, compiled and embedded at build time.
 *
 **********************************************************************/

#ifdef HAVE_METAL
#if defined(__APPLE__)

#import <Metal/Metal.h>
#import <Foundation/Foundation.h>
#include "../lwgeom_gpu.h"
#include "../lwgeom_log.h"
#include <string.h>
#include <math.h>

/* Embedded metallib generated by xxd -i at build time */
#include "gpu_metal_kernels_metallib.h"

/*
 * File-scope statics: cached Metal objects.
 * PostgreSQL runs one backend per process, so no locking needed.
 */
static int metal_initialized = 0;
static int metal_disabled = 0;
static char metal_device_name[256] = {0};

static id<MTLDevice> mtl_device = nil;
static id<MTLCommandQueue> mtl_queue = nil;
static id<MTLLibrary> mtl_library = nil;
static id<MTLComputePipelineState> mtl_pipeline_rotate_z = nil;
static id<MTLComputePipelineState> mtl_pipeline_rotate_z_m_epoch = nil;
static id<MTLComputePipelineState> mtl_pipeline_rad_convert = nil;

/**
 * Initialize the Metal GPU backend.
 * Creates device, command queue, loads embedded metallib, and
 * creates compute pipeline states for each kernel.
 *
 * Returns 1 on success, 0 on failure.
 */
int
lwgpu_metal_init(void)
{
	NSError *error = nil;
	id<MTLFunction> fn = nil;

	if (metal_initialized)
		return !metal_disabled;

	metal_initialized = 1;

	@autoreleasepool
	{
		/* Get the default Metal device */
		mtl_device = MTLCreateSystemDefaultDevice();
		if (!mtl_device)
		{
			LWDEBUG(1, "Metal: no GPU device found");
			metal_disabled = 1;
			return 0;
		}

		/* Cache device name */
		const char *name = [[mtl_device name] UTF8String];
		if (name)
			strncpy(metal_device_name, name, sizeof(metal_device_name) - 1);
		else
			strncpy(metal_device_name, "Apple GPU", sizeof(metal_device_name) - 1);

		/* Create command queue */
		mtl_queue = [mtl_device newCommandQueue];
		if (!mtl_queue)
		{
			LWDEBUG(1, "Metal: failed to create command queue");
			metal_disabled = 1;
			return 0;
		}

		/* Load embedded metallib */
		dispatch_data_t lib_data = dispatch_data_create(
			accel_gpu_metal_kernels_metallib,
			accel_gpu_metal_kernels_metallib_len,
			NULL,
			DISPATCH_DATA_DESTRUCTOR_DEFAULT);
		mtl_library = [mtl_device newLibraryWithData:lib_data error:&error];
		if (!mtl_library)
		{
			lwnotice("Metal: failed to load metallib: %s",
				 error ? [[error localizedDescription] UTF8String] : "unknown");
			metal_disabled = 1;
			return 0;
		}

		/* Create pipeline state for rotate_z_uniform kernel */
		fn = [mtl_library newFunctionWithName:@"rotate_z_uniform"];
		if (!fn)
		{
			lwnotice("Metal: kernel 'rotate_z_uniform' not found in metallib");
			metal_disabled = 1;
			return 0;
		}
		mtl_pipeline_rotate_z = [mtl_device newComputePipelineStateWithFunction:fn error:&error];
		if (!mtl_pipeline_rotate_z)
		{
			lwnotice("Metal: failed to create rotate_z pipeline: %s",
				 error ? [[error localizedDescription] UTF8String] : "unknown");
			metal_disabled = 1;
			return 0;
		}

		/* Create pipeline state for rotate_z_m_epoch kernel */
		fn = [mtl_library newFunctionWithName:@"rotate_z_m_epoch"];
		if (!fn)
		{
			lwnotice("Metal: kernel 'rotate_z_m_epoch' not found in metallib");
			metal_disabled = 1;
			return 0;
		}
		mtl_pipeline_rotate_z_m_epoch = [mtl_device newComputePipelineStateWithFunction:fn error:&error];
		if (!mtl_pipeline_rotate_z_m_epoch)
		{
			lwnotice("Metal: failed to create rotate_z_m_epoch pipeline: %s",
				 error ? [[error localizedDescription] UTF8String] : "unknown");
			metal_disabled = 1;
			return 0;
		}

		/* Create pipeline state for rad_convert kernel */
		fn = [mtl_library newFunctionWithName:@"rad_convert"];
		if (!fn)
		{
			lwnotice("Metal: kernel 'rad_convert' not found in metallib");
			metal_disabled = 1;
			return 0;
		}
		mtl_pipeline_rad_convert = [mtl_device newComputePipelineStateWithFunction:fn error:&error];
		if (!mtl_pipeline_rad_convert)
		{
			lwnotice("Metal: failed to create rad_convert pipeline: %s",
				 error ? [[error localizedDescription] UTF8String] : "unknown");
			metal_disabled = 1;
			return 0;
		}

		LWDEBUGF(1, "Metal: initialized on %s", metal_device_name);
	}

	return 1;
}

/**
 * Uniform-angle Z-rotation on GPU via Metal.
 *
 * @param data    Pointer to interleaved coordinate data
 * @param stride  Byte stride between consecutive points
 * @param n       Number of points
 * @param theta   Rotation angle in radians
 * @return 1 on success, 0 on failure (caller should fallback)
 */
int
lwgpu_metal_rotate_z(double *data, size_t stride, uint32_t n, double theta)
{
	/* TODO: implement Metal dispatch for uniform Z-rotation.
	 * Steps:
	 * 1. Compute cos_t/sin_t on CPU
	 * 2. Create MTLBuffer from data (zero-copy if page-aligned)
	 * 3. Create params buffer with stride/npoints/cos_t/sin_t
	 * 4. Encode compute command with rotate_z_uniform pipeline
	 * 5. Dispatch threads (threadgroup size 256)
	 * 6. Commit and waitUntilCompleted
	 * 7. Copy back if needed
	 */
	(void)data;
	(void)stride;
	(void)n;
	(void)theta;
	return 0;
}

/**
 * Per-point M-epoch Z-rotation on GPU via Metal.
 *
 * @param data     Pointer to interleaved xyzm data
 * @param stride   Byte stride between consecutive points
 * @param n        Number of points
 * @param m_off    Offset of M coordinate in doubles from point start
 * @param dir      -1 for ECI->ECEF, +1 for ECEF->ECI
 * @return 1 on success, 0 on failure (caller should fallback)
 */
int
lwgpu_metal_rotate_z_m_epoch(double *data, size_t stride, uint32_t n,
			     size_t m_off, int dir)
{
	/* TODO: implement Metal dispatch for per-epoch Z-rotation.
	 * Steps:
	 * 1. Create MTLBuffer from data (zero-copy if page-aligned)
	 * 2. Create params buffer with stride/npoints/m_offset/direction
	 * 3. Encode compute command with rotate_z_m_epoch pipeline
	 * 4. Dispatch threads, commit, wait
	 */
	(void)data;
	(void)stride;
	(void)n;
	(void)m_off;
	(void)dir;
	return 0;
}

/**
 * Shut down the Metal backend and release all resources.
 */
void
lwgpu_metal_shutdown(void)
{
	@autoreleasepool
	{
		mtl_pipeline_rad_convert = nil;
		mtl_pipeline_rotate_z_m_epoch = nil;
		mtl_pipeline_rotate_z = nil;
		mtl_library = nil;
		mtl_queue = nil;
		mtl_device = nil;
	}

	metal_initialized = 0;
	metal_disabled = 0;
	metal_device_name[0] = '\0';
}

/**
 * Return the cached Metal device name string.
 */
const char *
lwgpu_metal_device_name(void)
{
	return metal_device_name;
}

#endif /* __APPLE__ */
#endif /* HAVE_METAL */
